const glossary: Record<string, string> = {
  // Acronyms & abbreviations
  CLI: "Command Line Interface — a text-based tool for running commands on your computer, as opposed to a graphical interface.",
  PR: "Pull Request — a proposal to merge code changes into a shared branch. Team members review the changes before approving.",
  TDD: "Test-Driven Development — writing tests before writing the code they test. The cycle is: write a failing test, write code to pass it, then refactor.",
  "CI/CD": "Continuous Integration / Continuous Deployment — automated pipelines that build, test, and deploy your code whenever you push changes.",
  CI: "Continuous Integration — automatically building and testing code whenever changes are pushed to a shared repository.",
  MCP: "Model Context Protocol — an open standard for connecting AI tools to external services like databases, APIs, and dev tools.",
  API: "Application Programming Interface — a defined way for programs to communicate with each other, often over HTTP.",
  SDK: "Software Development Kit — a collection of tools, libraries, and documentation for building applications on a specific platform.",
  IDE: "Integrated Development Environment — a code editor with built-in tools like debugging, version control, and terminal access (e.g., VS Code, JetBrains).",
  RLS: "Row-Level Security — database rules that restrict which rows a user can access, so different users see different data from the same table.",
  ADR: "Architecture Decision Record — a short document capturing an important design decision, the context, and the reasoning behind it.",
  SSO: "Single Sign-On — letting users log in once to access multiple applications without re-entering credentials.",
  OAuth: "Open Authorization — a standard protocol that lets applications request limited access to a user's account on another service without seeing their password.",
  "E2E": "End-to-End testing — automated tests that simulate real user interactions (clicking, typing, navigating) to verify the full application works correctly.",
  LLM: "Large Language Model — an AI model trained on large amounts of text that can generate, analyze, and transform text and code.",
  RL: "Reinforcement Learning — a training method where the model learns by receiving rewards or penalties for its outputs.",
  CRUD: "Create, Read, Update, Delete — the four basic operations for working with data in a database or API.",
  XSS: "Cross-Site Scripting — a security vulnerability where attackers inject malicious scripts into web pages viewed by other users.",
  CWE: "Common Weakness Enumeration — a standardized list of software security weaknesses, each identified by a number (e.g., CWE-89 is SQL injection).",
  OWASP: "Open Web Application Security Project — a nonprofit that publishes widely-used security guidelines, including the 'Top 10' most critical web vulnerabilities.",
  CORS: "Cross-Origin Resource Sharing — a browser security mechanism that controls which websites can make requests to your server.",

  // Tools & technologies
  sandbox: "An isolated environment where code runs with restricted access to the rest of your system — if something goes wrong, it can't affect your real files or data.",
  linting: "Automated checking of code for style issues, potential bugs, and convention violations — like a spell-checker for code.",
  linter: "A tool that automatically checks code for style issues, potential bugs, and convention violations — like a spell-checker for code.",
  ESLint: "The standard linting tool for JavaScript and TypeScript. It catches errors, enforces code style, and can auto-fix many issues.",
  TypeScript: "A programming language that adds static type checking to JavaScript — it catches type-related bugs before your code runs.",
  Vitest: "A fast JavaScript/TypeScript testing framework, commonly used with modern projects. Similar to Jest but faster.",
  Playwright: "A browser automation framework for end-to-end testing — it can simulate real users clicking, typing, and navigating your app.",
  Zod: "A TypeScript library for validating data at runtime — ensures that data from APIs, forms, or external sources matches the shape you expect.",
  Semgrep: "A static analysis tool that scans code for security vulnerabilities and bug patterns without running it.",
  Gitleaks: "A tool that scans git repositories for accidentally committed secrets like API keys, passwords, and tokens.",
  Supabase: "An open-source backend platform providing a PostgreSQL database, authentication, file storage, and real-time subscriptions.",
  Vercel: "A cloud platform for deploying web applications, particularly optimized for Next.js projects.",
  "Next.js": "A React-based web framework that adds server rendering, file-based routing, and static site generation on top of React.",
  Turbopack: "Next.js's built-in bundler that compiles and packages your code for the browser. Successor to Webpack.",
  Docker: "A platform for running applications in containers — lightweight, isolated environments that package code with all its dependencies.",
  Prettier: "An opinionated code formatter that automatically reformats code to a consistent style. Handles spacing, line breaks, and quotes.",
  Tailwind: "Tailwind CSS — a utility-first CSS framework where you style elements by applying small, single-purpose classes directly in your HTML.",
  Sentry: "An error monitoring platform that captures and reports application errors in real time, with stack traces and context.",

  // Concepts
  "context window": "The maximum amount of text (measured in tokens) that an AI model can process at once. Longer conversations or larger codebases can exceed this limit.",
  token: "The basic unit of text that LLMs process — roughly 3/4 of a word. 'Hello world' is 2 tokens. Context windows and costs are measured in tokens.",
  hallucination: "When an AI generates information that sounds plausible but is factually incorrect — like referencing a function or package that doesn't exist.",
  prompt: "The text input you give to an AI model — your instructions, questions, or task descriptions that tell it what to do.",
  "feature branch": "A separate line of development in git where you build a new feature without affecting the main codebase until it's ready.",
  worktree: "A git feature that lets you have multiple branches checked out simultaneously in different directories, so you can work on parallel tasks.",
  "conventional commits": "A naming convention for git commits that uses prefixes like feat:, fix:, docs: to categorize changes and enable automated tooling.",
  "strict mode": "A TypeScript compiler setting that enables all strict type-checking options, catching more potential bugs at compile time.",
  "mutation testing": "A testing technique that introduces small bugs (mutations) into your code to verify that your tests actually catch them.",
  "static generation": "Building all web pages at compile time rather than on each request — the result is plain HTML files that load instantly.",
  "parameterized queries": "Database queries where user input is passed as parameters rather than concatenated into the query string, preventing SQL injection attacks.",
  containerized: "Running inside a container — a lightweight, isolated environment with its own filesystem and network, separate from the host system.",
  compaction: "The process of summarizing earlier parts of a conversation to free up context window space while preserving key information.",
};

export default glossary;
